import { NextRequest, NextResponse } from 'next/server'
//import { ElevenLabsClient } from 'elevenlabs'
import { createClient } from '@supabase/supabase-js'

//const eleven = new ElevenLabsClient({ apiKey: process.env.ELEVENLABS_API_KEY! })
const supabase = createClient(process.env.SUPABASE_URL!, process.env.SUPABASE_ANON_KEY!);

// This endpoint was generated by AI and is not currently used. Some of the functionality has been intentionally disabled

export async function POST(req: NextRequest) {
  const { bookId } = await req.json()
  const { data: book } = await supabase.from('books').select('*').eq('id', bookId).single()

  if (!book) return new Response('Book not found', { status: 404 })

  /* const audio = await eleven.textToSpeech({
    voiceId: 'Rachel', // default voice
    modelId: 'eleven_monolingual_v1',
    text: `${book.title}. ${book.description}`,
  }) */

  //return NextResponse.json({ url: audio.audioUrl });
  return NextResponse.json({success: true}); // Dummy output
}
