'use client'
//import { useState } from 'react'
import { Box, Typography, Button, CircularProgress, Alert } from '@mui/material'
//import { useSearchParams } from 'next/navigation';

// This page was generated by AI and currently is not used. Kept for reference

export default function ThankYouPage() {
  //const searchParams = useSearchParams()
  //const bookId = searchParams.get('bookId')
  //const [pdfUrl, setPdfUrl] = useState('')
  //const [loading, setLoading] = useState(true)

  /* useEffect(() => {
    async function fetchPdfUrl() {
      if (!bookId) return

      // In production, replace with actual fetch from Supabase or DB
      const res = await fetch(`/api/fetch-book-url?bookId=${bookId}`)
      const data = await res.json()
      setPdfUrl(data.url)
      setLoading(false)
    }

    fetchPdfUrl()
  }, [bookId]) */

  // Dummy values to get rid of build errors
  const loading = false;
  const pdfUrl = 'some-dummy-string';
  const bookId = '12345';

  return (
      <Box sx={{ textAlign: 'center', mt: 6 }}>
        <Typography variant="h4" gutterBottom>Thank You for Your Purchase!</Typography>
        {loading && <CircularProgress />}
        {!loading && pdfUrl && (
          <>
            <Alert severity="success" sx={{ mt: 3 }}>
              Your book is ready. Click below to download it.
            </Alert>
            <Button
              variant="contained"
              color="primary"
              size="large"
              href={pdfUrl}
              target="_blank"
              sx={{ mt: 4 }}
            >
              Download Your Book
            </Button>

            <Typography variant="h6" sx={{ mt: 5 }}>Want a printed copy or narration?</Typography>
            <Button
              variant="outlined"
              href={`/print/${bookId}`}
              sx={{ mt: 2, mr: 2 }}
            >
              📦 Print Edition
            </Button>
            <Button
              variant="outlined"
              href={`/narrate/${bookId}`}
              sx={{ mt: 2 }}
            >
              🎧 Narrated Audio
            </Button>
          </>
        )}
      </Box>
  )
}
